from fpdf import FPDF
import datetime

class CourtReportPDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 15)
        self.cell(0, 10, 'OFFICIAL CHAIN OF CUSTODY COURT REPORT', 0, 1, 'C')
        self.set_font('Arial', 'I', 10)
        self.cell(0, 10, 'Generated by Forensic CoC System - Cryptographically Verified', 0, 1, 'C')
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

def generate_pdf_report(evidence_id, audit_trail, output_filename="court_report.pdf"):
    """
    Takes the SQL audit trail and generates a professional PDF.
    """
    pdf = CourtReportPDF()
    pdf.add_page()
    
    # --- Meta Information ---
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, f"Evidence ID: {evidence_id}", 0, 1)
    pdf.set_font('Arial', '', 10)
    pdf.cell(0, 10, f"Report Generated: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", 0, 1)
    pdf.ln(5)
    
    # --- Table Header ---
    pdf.set_font('Arial', 'B', 10)
    pdf.cell(40, 10, 'Date & Time', 1)
    pdf.cell(30, 10, 'Relinquished', 1)
    pdf.cell(30, 10, 'Received', 1)
    pdf.cell(40, 10, 'Reason', 1)
    pdf.cell(50, 10, 'Hash Signature (Truncated)', 1)
    pdf.ln()
    
    # --- Table Body ---
    pdf.set_font('Arial', '', 9)
    for record in audit_trail:
        # Convert dictionary keys to match your db_manager SQL query
        time_str = str(record.get('Date & Time', ''))
        relinq = str(record.get('Relinquished By', ''))
        recv = str(record.get('Received By', ''))
        reason = str(record.get('Reason/Action', ''))
        # Truncate hash so it fits on the PDF page
        full_hash = str(record.get('Cryptographic Signature', ''))
        short_hash = full_hash[:15] + "..." if len(full_hash) > 15 else full_hash
        
        pdf.cell(40, 10, time_str, 1)
        pdf.cell(30, 10, relinq, 1)
        pdf.cell(30, 10, recv, 1)
        pdf.cell(40, 10, reason, 1)
        pdf.cell(50, 10, short_hash, 1)
        pdf.ln()
        
    pdf.output(output_filename)
    return output_filename
